<?php
/*
    Shopix_ProductExpiration - Make product unavailable after a configured date and time
    Copyright (C) 2013 Shopix Pty Ltd (http://www.shopix.com.au)

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
?>
<?php
$_time_left = Mage::helper('productexpiration')->getProductTimeLeft($this->getProduct(), true);
?>
<?php if (! is_null($_time_left)): ?>
    <?php if ($_time_left['expired']): ?>
        <p class="timer hasCountdown"><span class="expired"><?php echo $this->__('Expired') ?></span></p>
    <?php else: ?>
        <p class="timer" data-hour="<?php echo $_time_left['hour'] ?>" data-min="<?php echo $_time_left['min'] ?>" data-sec="<?php echo $_time_left['sec'] ?>"><?php echo $this->__('Expires in ') . sprintf('%s:%s', $_time_left['hour'], $_time_left['min']) ?></p>
    <?php endif; ?>
<?php endif; ?>
